"""Extract causal states, train discounted-risk regressors, report held-out risk curves."""
import argparse
import hashlib
import json
import random
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import numpy as np
import torch
from foresteer.core import RiskPredictor, windowed_cost
from foresteer.termination import cached_termination_flags, is_terminated, model_eos_ids


def save_json(path, value):
    Path(path).write_text(json.dumps(value, indent=2)+'\n')


def extract(args):
    from model import build_model
    from foresteer.replay import replay
    if (args.output/'manifest.json').exists():
        raise FileExistsError('Completed extraction exists; choose a new --output directory')
    records = [json.loads(x) for x in Path(args.input).read_text().splitlines() if x.strip()]
    if args.max_samples:
        records = records[:args.max_samples]
    if not records:
        raise ValueError('No training records')
    image_ids = sorted({r['image_id'] for r in records})
    random.Random(args.seed).shuffle(image_ids)
    n = len(image_ids)
    if n != len(records):
        raise ValueError('Expected one trajectory per image; duplicate image IDs found')
    splits = {v: ('train' if i < int(.7*n) else 'val' if i < int(.85*n) else 'test') for i,v in enumerate(image_ids)}
    manifest = dict(input=str(Path(args.input).resolve()), input_sha256=hashlib.sha256(Path(args.input).read_bytes()).hexdigest(),
                    model_path=str(Path(args.model_path).resolve()), model_name=args.model_name, layers=args.layers, seed=args.seed,
                    num_shards=args.num_shards, shard_index=args.shard_index, total_records=len(records), records=[])
    assigned = list(enumerate(records))[args.shard_index::args.num_shards]
    if assigned:
        adapter = build_model(args)
        adapter.model.eval().requires_grad_(False)
    eos_ids = model_eos_ids(args.model_path)
    for local_index, (i, record) in enumerate(assigned):
        if Path(record['model']['path']).resolve() != Path(args.model_path).resolve():
            raise ValueError('Training trajectories were generated by a different model')
        features, labels = replay(adapter, record, str(Path(args.coco_root)/record['image_file']), args.layers, validate=local_index < 3)
        file = f'states/{i:06d}.pt'
        terminated = is_terminated(record, eos_ids)
        torch.save(dict(features=features, labels=labels, terminated=terminated), args.output/file)
        manifest['records'].append(dict(file=file, index=i, image_id=record['image_id'], split=splits[record['image_id']], terminated=terminated))
        if local_index % 25 == 0:
            print(f'Shard {args.shard_index}: extracted {local_index+1}/{len(assigned)}', flush=True)
    name = 'manifest.json' if args.num_shards == 1 else f'manifest.shard-{args.shard_index}-of-{args.num_shards}.json'
    save_json(args.output/name, manifest)


def train(args):
    torch.set_num_threads(4)
    torch.manual_seed(args.seed)
    features_dir = args.features_dir or args.output
    manifest = json.loads((features_dir/'manifest.json').read_text())
    termination = cached_termination_flags(manifest)
    data = {k: [[], [], []] for k in ('train','val','test')}
    counts = {k: dict(total_tokens=0, used_tokens=0, masked_tokens=0, terminal_images=0, truncated_images=0) for k in data}
    for row in manifest['records']:
        item = torch.load(features_dir/row['file'], map_location='cpu')
        x = item['features'][args.layer]
        terminated = termination[row['image_id']]
        y, valid = windowed_cost(item['labels'], args.gamma, args.risk_horizon, terminated=terminated)
        if len(x) != len(y):
            raise ValueError('Feature/label length mismatch')
        count = counts[row['split']]
        count['total_tokens'] += len(y)
        count['used_tokens'] += int(valid.sum())
        count['masked_tokens'] += int((~valid).sum())
        count['terminal_images' if terminated else 'truncated_images'] += 1
        distances = []
        future = None
        for i in reversed(range(len(y))):
            if item['labels'][i]: future = i
            distances.append(-1 if future is None else future-i)
        dest = data[row['split']]
        dest[0].append(x[valid]); dest[1].append(y[valid])
        dest[2].extend(np.array(distances[::-1])[valid.numpy()])
    for split, values in data.items():
        if not counts[split]['used_tokens']:
            raise ValueError(f'No observable {args.risk_horizon}-token targets in {split} split')
        data[split] = (torch.cat(values[0]), torch.cat(values[1]), np.array(values[2]))
    width = data['train'][0].shape[1]
    if args.epochs < 1 or args.patience < 1:
        raise ValueError('epochs and patience must be positive')
    model = RiskPredictor(width, args.hidden).to(args.device)
    opt = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=1e-4)
    loader = torch.utils.data.DataLoader(torch.utils.data.TensorDataset(*data['train'][:2]), batch_size=args.batch_size, shuffle=True)
    def predict(split):
        model.eval()
        with torch.no_grad():
            return torch.cat([model(x.to(args.device).float()).cpu() for x in data[split][0].split(args.batch_size)])
    best, stale, history = float('inf'), 0, []
    checkpoint = args.output/f'risk_layer{args.layer}_gamma{args.gamma}_h{args.risk_horizon}_seed{args.seed}.pt'
    for epoch in range(args.epochs):
        model.train()
        total = 0.
        for x,y in loader:
            opt.zero_grad(set_to_none=True)
            loss = torch.nn.functional.smooth_l1_loss(model(x.to(args.device).float()), y.to(args.device))
            loss.backward(); opt.step()
            total += loss.item()*len(y)
        val = torch.nn.functional.smooth_l1_loss(predict('val'), data['val'][1]).item()
        if not np.isfinite(val):
            raise FloatingPointError('Nonfinite validation loss')
        history.append(dict(epoch=epoch+1, train_loss=total/len(data['train'][1]), val_loss=val))
        print(history[-1], flush=True)
        if val < best:
            best, stale = val, 0
            torch.save(dict(schema='foresteer.risk.v2', risk_horizon=args.risk_horizon,
                            target='finite_window_discounted_cost', mask_policy='full_window_or_true_terminal', state_dict={k:v.detach().cpu() for k,v in model.state_dict().items()},
                            width=width, hidden=args.hidden, layer=args.layer, gamma=args.gamma,
                            model_path=manifest['model_path'], model_name=manifest['model_name'],
                            seed=args.seed, best_epoch=epoch+1, input_sha256=manifest['input_sha256']), checkpoint)
        else:
            stale += 1
            if stale >= args.patience: break
    model.load_state_dict(torch.load(checkpoint, map_location=args.device)['state_dict'])
    p, y, distances = predict('test'), data['test'][1], data['test'][2]
    report = dict(checkpoint=str(checkpoint), risk_horizon=args.risk_horizon,
                  target='finite_window_discounted_cost', token_counts=counts, history=history, test_mse=float(((p-y)**2).mean()),
                  test_smooth_l1=float(torch.nn.functional.smooth_l1_loss(p,y)), distance_to_next_onset=[])
    for d in [-1,0,1,2,4,8,16,32]:
        mask = distances == d
        if mask.any():
            report['distance_to_next_onset'].append(dict(distance=d, count=int(mask.sum()), prediction=float(p[mask].mean()), target=float(y[mask].mean())))
    np.savez(checkpoint.with_suffix('.predictions.npz'), prediction=p.numpy(), target=y.numpy(), distance=distances)
    save_json(checkpoint.with_suffix('.json'), report)
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    rows = [r for r in report['distance_to_next_onset'] if r['distance'] >= 0]
    fig, ax = plt.subplots(figsize=(6,4))
    for key in ('prediction','target'):
        ax.plot([r['distance'] for r in rows], [r[key] for r in rows], 'o-', label=key)
    ax.set(xlabel='Actions until next hallucination onset (0 = next token)', ylabel='Discounted risk',
           title=f'Block {args.layer}, gamma={args.gamma}, H={args.risk_horizon}, held-out images')
    ax.legend(); fig.tight_layout(); fig.savefig(checkpoint.with_suffix('.png'), dpi=160); plt.close(fig)


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('stage', choices=['extract','train'])
    p.add_argument('--input', default='outputs/llava_coco_train2014/chair_tokens.jsonl')
    p.add_argument('--output', type=Path)
    p.add_argument('--features-dir', type=Path, help='Training feature source; defaults to --output')
    p.add_argument('--model-name', default='llava')
    p.add_argument('--model-path', default=str(Path.home()/'models/llava-v1.5-7b'))
    p.add_argument('--coco-root', default=str(Path.home()/'dataset/coco'))
    p.add_argument('--device', default='cuda')
    p.add_argument('--layers', type=int, nargs='+', default=[16,32])
    p.add_argument('--layer', type=int, default=16)
    p.add_argument('--gamma', type=float, default=.9)
    p.add_argument('--risk-horizon', type=int, default=16, help='Future action window; mask incomplete windows at length stops')
    p.add_argument('--seed', type=int, default=42)
    p.add_argument('--max-samples', type=int)
    p.add_argument('--num-shards', type=int, default=1)
    p.add_argument('--shard-index', type=int, default=0)
    p.add_argument('--hidden', type=int, default=256)
    p.add_argument('--epochs', type=int, default=50)
    p.add_argument('--patience', type=int, default=5)
    p.add_argument('--batch-size', type=int, default=1024)
    p.add_argument('--lr', type=float, default=1e-4)
    args=p.parse_args()
    if args.output is None:
        name = args.model_name.lower().replace('_', '-')
        name = {'qwen-vl': 'qwen-vl-chat', 'qwenvl': 'qwen-vl-chat',
                'qwenvlchat': 'qwen-vl-chat', 'mplugowl2': 'mplug-owl2',
                'llava-7b': 'llava', 'llava-v1.5-7b': 'llava'}.get(name, name)
        args.output = Path('outputs/risk')/name
    if args.num_shards < 1 or not 0 <= args.shard_index < args.num_shards:
        p.error('Require num-shards >= 1 and 0 <= shard-index < num-shards')
    if args.risk_horizon < 1:
        p.error("--risk-horizon must be positive")
    args.temperature=0.; args.num_beams=1; args.max_length=128; args.top_p=None; args.top_k=None
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output/'states').mkdir(exist_ok=True)
    (extract if args.stage=='extract' else train)(args)

if __name__=='__main__': main()
